# Generated by Django 2.2.2 on 2019-06-16 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=280)),
            ],
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('country', models.CharField(choices=[('GB', 'United Kingdom'), ('US', ' United States of America'), ('JP', 'Japan')], max_length=2)),
                ('last_login', models.DateTimeField()),
                ('devices', models.ManyToManyField(to='testers.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testers.Device')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testers.Tester')),
            ],
        ),
    ]
