version: '3'

services:
  db:
    image: postgres
    volumes:
# Windows:
#      - tester-postgresql:/var/lib/postgresql/data
# Non windows:
      - ./postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - dev.env
    depends_on:
      - db
# Windows:
#volumes:
#  tester-postgresql:
#    external: true