version: '3'

services:
  db:
    image: postgres:9.6.21
    volumes:
      - prod-tester-postgresql:/var/lib/postgresql/data
    container_name: prod_db
    env_file:
      - db.env
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn TesterMatch.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - .:/code
      - prod-django-static:/code/static
    expose:
      - 8000
    env_file:
      - prod.env
      - db.env
    depends_on:
      - db
    container_name: prod_web
  nginx:
    build: ./nginx
    volumes:
      - prod-django-static:/usr/src/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
    container_name: prod_nginx
volumes:
  prod-tester-postgresql:
  prod-django-static: