version: '3'

services:
  db:
    image: postgres:9.6.21
    volumes:
      - tester-postgresql:/var/lib/postgresql/data
    env_file:
      - db.env
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - dev.env
      - db.env
    depends_on:
      - db
volumes:
  tester-postgresql:
